Added communications data
fabianhjr/awesome-radical-decentralization pull request #2
Opened 2019-02-03 02:22 UTC by J0MS

Added useful info about open source communication software.

2019-02-04 19:55 UTC, fabianhjr requested changes
Please remove the two projects out of scope or counterargue for their inclusion as decentralization projects.

2019-02-04 19:55 UTC, fabianhjr commented on projects/infrastructure/comunications/README.md
> +### [wireguard VPN Tunnel](https://www.wireguard.com/)
VPN services don't fit the scope.

2019-02-04 19:55 UTC, fabianhjr commented on projects/decentralized-applications/README.md
> +## [Diaspora*](https://diasporafoundation.org/)
Diaspora is federated not decentralized. (Like activitypub/mastodon/etc)

2019-02-06 03:22 UTC, J0MS commented on projects/infrastructure/comunications/README.md
> +### [wireguard VPN Tunnel](https://www.wireguard.com/)
Understood ;), I moved Wireguard into ->  projects/decentralized-applications/
```suggestion
### [wireguard VPN Tunnel](https://www.wireguard.com/)
```
It is ok, or Wireguard must be removed? What do you think?

2019-02-06 03:22 UTC, J0MS commented on projects/decentralized-applications/README.md
> +## [Diaspora*](https://diasporafoundation.org/)
Ok, removed Diaspora*

2019-02-10 04:20 UTC, J0MS commented
@fabianhjr 
Changes made ;)

2019-02-10 23:13 UTC, merged